apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console-ui.fullname" . }}
  labels: {{- include "console-ui.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{ .Values.consoleUi.config | nindent 4 }}
  environment.js: |-
    {{ .Values.consoleUi.environment | nindent 4 }}
  {{- if .Values.consoleUi.themeOverride }}
  theme-override.css: |-
    {{ .Values.consoleUi.themeOverride | nindent 4 }}
  {{- end }}
