apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superphenix-console.fullname" . }}
  labels: {{- include "superphenix-console.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{ .Values.console.config | nindent 4 }}
  environment.js: |-
    {{ .Values.console.environment | nindent 4 }}
  {{- if .Values.console.themeOverride }}
  theme-override.css: |-
    {{ .Values.console.themeOverride | nindent 4 }}
  {{- end }}
