apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superphenix-console.fullname" . }}
  labels: {{- include "superphenix-console.labels" . | nindent 4 }}
data:
  {{- if .Values.config.nginxConf }}
  nginx.conf: |-
    {{ .Values.config.nginxConf | nindent 4 }}
  {{- end }}
  environment.js: |-
    window.$environment = {
      production: {{ .Values.config.production }},
      appName: {{ .Values.config.appName | quote }},
      apiUrl: {{ .Values.config.apiUrl | quote }},
      authUrl: {{ .Values.config.authUrl | quote }},
      ssl: {{ .Values.config.ssl }},
      sessionAutoRenew: {{ .Values.config.sessionAutoRenew }},
      supportEmail: {{ .Values.config.supportEmail | quote }},
      helpLinks: [
        {{- range $key, $val := .Values.config.helpLinks }}
        { icon: {{ $val.icon | quote }}, text: {{ $val.text | quote }}, url: {{ $val.url | quote }} },
        {{- end }}
      ],
    };
  {{- if .Values.config.themeOverride }}
  theme-override.css: |-
    {{ .Values.config.themeOverride | nindent 4 }}
  {{- end }}
