import { Clipboard } from '@angular/cdk/clipboard';
import { KeyValuePipe } from '@angular/common';
import { Component, computed, inject } from '@angular/core';
import { rxResource, toSignal } from '@angular/core/rxjs-interop';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatDialog } from '@angular/material/dialog';
import { MatDividerModule } from '@angular/material/divider';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar } from '@angular/material/snack-bar';
import { MatTableModule } from '@angular/material/table';
import { MatTabsModule } from '@angular/material/tabs';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { TabsBase } from '@products/00_shared/components/tabs-base/tab-base.component';
import { policyDst, policySrc, StaticRoute } from '@products/00_shared/models/network/vpc/vpc.model';
import { ProductSubnet } from '@products/00_shared/models/product.model';
import { SubnetService } from '@products/00_shared/services/subnet.service';
import { VPCService } from '@products/00_shared/services/vpc.service';
import { getProductLabelInfo } from '@products/00_shared/utils/product-label-utils';
import { BannerComponent } from '@shared/components/banner/banner.component';
import { ContentHeaderComponent } from '@shared/components/content-header/content-header.component';
import { SpanCopyComponent } from '@shared/components/span-copy/span-copy.component';
import { GridDirective } from '@shared/directives/grid.directive';
import { PRA_LABEL_KEYS } from '@shared/models/consts';
import { BannerLevelEnum } from '@shared/models/enums';
import { PermissionsEnum } from '@shared/models/permissions/permission.enum';
import { PermissionService } from '@shared/services/permission.service';
import { StateService } from '@shared/services/state.service';
import { forkJoin, Observable, of } from 'rxjs';
import { VpcActions } from '../vpc-actions.utils';
import { environment } from '@env/environment';

class StaticRouteDisplay implements StaticRoute {
  policy!: typeof policySrc | typeof policyDst;
  cidr!: string;
  nextHopIP!: string;
  routeTable!: string;
  autoGenerated!: boolean;
  subnet?: ProductSubnet;
}

@Component({
  selector: 'spx-vpc-details',
  imports: [
    MatCardModule,
    MatButtonModule,
    MatMenuModule,
    MatDividerModule,
    MatTabsModule,
    MatIconModule,
    ContentHeaderComponent,
    MatChipsModule,
    MatTableModule,
    MatProgressSpinnerModule,
    RouterLink,
    BannerComponent,
    SpanCopyComponent,
    GridDirective,
    KeyValuePipe,
  ],
  templateUrl: './vpc-details.component.html',
  styleUrl: './vpc-details.component.scss',
})
export class VpcDetailsComponent extends TabsBase {
  protected stateSvc = inject(StateService);
  protected permissionSvc = inject(PermissionService);
  protected vpcSvc = inject(VPCService);
  protected subnetSvc = inject(SubnetService);
  protected clipboard = inject(Clipboard);
  private readonly dialog = inject(MatDialog);
  private readonly snackbar = inject(MatSnackBar);
  protected readonly supportEmail = environment.supportEmail;
  protected readonly policyDst = policyDst;
  BannerLevelEnum = BannerLevelEnum;
  az = computed(() => {
    return this.routeParams()?.['az'];
  });

  canProjectVPCWrite = computed(() => this.permissionSvc.permissions().includes(PermissionsEnum.ProjectVPCWrite));
  canProjectSubnetRead = computed(() => this.permissionSvc.permissions().includes(PermissionsEnum.ProjectSubnetRead));
  canProjectSubnetWrite = computed(() => this.permissionSvc.permissions().includes(PermissionsEnum.ProjectSubnetWrite));
  canProjectArgoCdRead = computed(() => this.permissionSvc.permissions().includes(PermissionsEnum.ProjectArgoCdRead));

  routeParams;
  vpcProduct = rxResource({
    params: computed(() => [this.stateSvc.project(), this.stateSvc.organization(), this.routeParams()]),
    stream: () => {
      const az = this.routeParams()?.['az'];
      const id = this.routeParams()?.['id'];

      if (this.stateSvc.organization() && this.stateSvc.project() && id) {
        return this.vpcSvc.get(this.stateSvc.organization()!.id, this.stateSvc.project()!.id, az, id);
      } else {
        return of();
      }
    },
  });

  isPRA = computed(() => {
    if (this.vpcProduct.hasValue()) {
      if (this.vpcProduct.value().vpc?.metadata.labels) {
        return Object.keys(this.vpcProduct.value().vpc!.metadata.labels!).some(v => PRA_LABEL_KEYS.includes(v));
      }
    }

    return false;
  });

  productLabelInfo = computed(() => {
    if (this.vpcProduct.hasValue()) {
      return getProductLabelInfo(this.vpcProduct.value().vpc?.metadata?.labels);
    }
    return getProductLabelInfo();
  });

  subnetsProduct = rxResource({
    params: () => (this.vpcProduct.hasValue() ? this.vpcProduct.value().vpc?.status.subnets : undefined),
    stream: ({ params }) => {
      // If the user can't read subnets, then don't try to fetch them
      if (!this.canProjectSubnetRead()) {
        return of([]);
      }

      const subnetIds = params || [];
      const obs: Observable<ProductSubnet>[] = [];
      subnetIds.forEach(id => {
        obs.push(this.subnetSvc.get(this.stateSvc.organization()!.id, this.stateSvc.project()!.id, this.az(), id));
      });
      return forkJoin(obs);
    },
  });

  staticRoutes = computed<StaticRouteDisplay[]>(() => {
    if (this.vpcProduct.hasValue()) {
      let staticRoutes = this.vpcProduct.value().vpc?.spec.staticRoutes as StaticRouteDisplay[];

      if (staticRoutes && this.subnetsProduct.hasValue()) {
        staticRoutes = staticRoutes.map(el => {
          const sub = this.subnetsProduct.value()?.find(s => s.eid === el.routeTable);
          el.subnet = sub;
          return el;
        });
      }

      return staticRoutes || [];
    } else {
      return [];
    }
  });

  staticRoutesColumns = computed(() => {
    const colums = ['policy', 'cidr', 'nextHop', 'subnet', 'autoGenerated'];
    if (this.canProjectSubnetRead()) {
      colums.push('actions');
    }
    return colums;
  });
  // staticRoutesColumns: string[] = ['policy', 'cidr', 'nextHop', 'subnet', 'autoGenerated', 'actions'];
  subnetColumns: string[] = ['id', 'name', 'cidr', 'actions'];

  constructor() {
    super();
    const route = inject(ActivatedRoute);

    this.routeParams = toSignal(route.params);
  }

  copy(value: string) {
    this.clipboard.copy(value);
    this.snackbar.open('Copy to clipboard!', undefined, {
      horizontalPosition: 'end',
      duration: 3000,
    });
  }

  addSubnet() {
    if (this.vpcProduct.hasValue()) {
      VpcActions.addSubnet(this.router, this.az(), this.vpcProduct.value());
    }
  }

  copyShareLink() {
    const url = `https://${window.location.host}/redirect/${this.stateSvc.organization()?.id}/${this.stateSvc.project()?.id}/${this.az()}/vpc/${this.routeParams()?.['id']}`;
    this.copy(url);
  }

  openArgoCD() {
    if (this.vpcProduct.hasValue()) {
      VpcActions.openArgoCD(this.vpcSvc, this.stateSvc, this.az(), this.vpcProduct.value());
    }
  }

  deleteVPC() {
    if (this.vpcProduct.hasValue()) {
      VpcActions.deleteVPC(this.vpcSvc, this.stateSvc, this.dialog, this.az(), this.vpcProduct.value()).then(res => {
        if (res) {
          this.router.navigate(['/products', 'network', 'vpc']);
        }
      });
    }
  }
}
