import { Condition, ObjectMeta } from '../../common.model';

export const policySrc = 'policySrc';
export const policyDst = 'policyDst';

export interface VPC {
  kind: string;
  apiVersion: string;
  metadata: ObjectMeta;
  spec: VPCSpec;
  status: VPCStatus;
}

interface VPCSpec {
  staticRoutes: StaticRoute[];
}

interface VPCStatus {
  // Conditions represents the latest state of the object
  conditions: Condition[];
  subnets: string[];
}

export interface StaticRoute {
  policy: typeof policySrc | typeof policyDst;
  cidr: string;
  nextHopIP: string;
  routeTable: string;
  autoGenerated?: boolean;
}
